# Setup
title:        CIAS Class Cal
tagline:      A scheduling system that transcends space and time
baseurl:      "~classcal"
locale:       "en"

# About/contact
author:
  name:       The Team
  url:        se.rit.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

#Others
markdown: kramdown
